### PR TITLE
Tokenize credit card

### PR DESCRIPTION
**Pull request by dvdnhm**
I needed this function in the library.. So here it is.

details are on: https://developer.payeezy.com/payeezy-api/apis/post/transactions/tokens

### CODE REVIEW

**Comment by bsclifton** [comment]
@dvdnhm looks like you added the feature, but then reverted it? was this intentional? I can help you drop the revert commit 😄 Just let me know

**Comment by dvdnhm** [comment]
I forgot to commit it to a new branch, so reverted and committed to a new branch but somehow the new branch shows the reverted one too.

'Revert' is still something I can't use properly :)

Help would be appreciated.

**Comment by bsclifton** [comment]
@dvdnhm I removed your revert commit- looks like there's a conflict though that needs to be resolved. I'll help you resolve this- stay tuned

Can you confirm the changes in this pull request are the ones you made? (everything looks good?)

**Comment by dvdnhm** [comment]
I made small changes in the files and re-sent them. I hope it would help.

**Comment by bsclifton** [comment]
@dvdnhm I had to rebase your PR; can you grab latest and give it a shot?

If you do a `git pull`, you'll likely get a conflict. So you can do:
```
git fetch origin
git reset --hard origin/tokenizeCreditCard
```

After doing that, you should be able to confirm your changes are there 😄 Unfortunately, I don't have Visual Studio setup on my laptop at the moment

**Pull request closed without merging**
